name: Update snapshot

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: |
          npm ci
          npm run test -- -u
        working-directory: ./cdk
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "cdk/test/__snapshots__/."
          message: "update snapshot"
